
# Data and Methods

```{r load_packages_and_df}
library(tidyverse)
library(here)
library(knitr) # for kable
load(here("data", "df.Rda"))
```

```{r variable_ordering}
################################
# Disability Variable Ordering #
################################
base_disability_list <- c("disability_percent_under5", "disability_percent_5to17", "disability_percent_18to34", "disability_percent_35to64", "disability_percent_65to74", "disability_percent_75andup")

# adds a suffix to a string
# used for generating the male and female disability lists
add_suffix <- function(string, suffix) {
  string <- paste0(string, suffix)
  string
}

# create male, female, and unified disability variable ordering list
# and then turn them back into usable vectors
# instead of lists (to avoid the [[]] nonsense and ambiguity with tidyselect)
male_disability_ordering <- base_disability_list %>%
  map(add_suffix, "_male") %>%
  as.character()
female_disability_ordering <- base_disability_list %>%
  map(add_suffix, "_female") %>%
  as.character()
disability_ordering <- c(male_disability_ordering, female_disability_ordering)

###############################
# Education Variable Ordering #
###############################
education_ordering <- c("education_b_percent_highschool_or_less", "education_b_percent_college_or_more",
                        "education_s_percent_less_than_highschool", "education_s_percent_highschool",
                        "education_s_percent_ged", "education_s_percent_some_college", "education_s_percent_college",
                        "education_s_percent_graduate")

############################
# Master Variable Ordering #
############################
misc_variable_ordering <- c("OD_rate", "income_pc_individual", "percent_white", "percent_black", "population", "deaths")
master_variable_ordering <- c(misc_variable_ordering, education_ordering, disability_ordering)
```

```{r summary_stats_all_variables, results="asis"}
df %>%
  select(-GEOID, -county, -year) %>%
  select(all_of(master_variable_ordering)) %>%
  summarize_all(list(min, max, mean, sd), na.rm = TRUE) %>%
  pivot_longer(everything()) %>% # turns into a 2 column df
  mutate(func = str_match(name, "_fn([1-4])")[,2]) %>% # func identifies which transformation was used
  mutate(func = case_when(func == 1 ~ "Min", # converts func into a meaninful label
                          func == 2 ~ "Max",
                          func == 3 ~ "Mean",
                          func == 4 ~ "Standard Deviation")) %>%
  mutate(name = str_remove(name, "_fn[1-4]")) %>% # strips the suffix which was turned into func
  pivot_wider(names_from = func, values_from = "value") %>% # untidies but makes easy to use
  mutate(`Variable Name` = name, # make the variable name label better
         name = NULL) %>%
  select(`Variable Name`, everything()) %>% # gets the variable name in front
  kable(caption = "Summary statistics of all variables used in analysis",
        format.args = list(scientific = FALSE,
                           big.mark = ","))
```

```{r OD_rate_distribution}
df %>%
  filter(!is.na(OD_rate)) %>% # drop the NA rows that occur because of the missing 2018 deaths data
  ggplot(aes(x = OD_rate)) +
  geom_histogram(bins = 25) +
  theme_minimal() +
  ggtitle("Distribution of Overdose Rate") +
  labs(y = "", x = "Overdose Rate (Deaths per 10,000)") +
  theme(axis.text.y = element_blank(),
        plot.title = element_text(hjust = 0.5))
```

Consider tobit (sp?) model due to censoring.

```{r county_racial_distribution}
df %>%
  ggplot(aes(x = percent_black)) +
  geom_histogram(bins = 20) +
  theme_minimal() +
  ggtitle("Distribution of Percent Black") +
  labs(x = "Percent Black", y = "") +
  scale_x_continuous(labels = function(x) paste0(x, "%")) + # adds percentage signs; scales::percent assumes .XXX format, while I have XX.X
  theme(axis.text.y = element_blank(),
        plot.title = element_text(hjust = 0.5))
```