```{r include_packages_2, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis and also two functions
# used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(dplyr))
    install.packages("dplyr", repos = "http://cran.rstudio.com")
if(!require(ggplot2))
    install.packages("ggplot2", repos = "http://cran.rstudio.com")
if(!require(ggplot2))
    install.packages("bookdown", repos = "http://cran.rstudio.com")
if(!require(thesisdown)){
  library(devtools)
  devtools::install_github("ismayc/thesisdown")
  }
library(thesisdown)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(citr)
```

```{r install_packages}
library(broom)
library(tidyverse)
library(here)
library(knitr) # for kable
load(here("data", "df.Rda"))
```

# Results

## Basic Model With All Counties Included in Data
```{r}
# formula used throughout chapter 3 as of right now
basic_regression_formula <- formula(OD_rate ~ income_pc_individual + percent_black + education_b_percent_highschool_or_less + education_b_percent_college_or_more + disability_percent_5to17_male + disability_percent_18to34_male + disability_percent_35to64_male + disability_percent_65to74_male + disability_percent_5to17_female + disability_percent_18to34_female + disability_percent_35to64_female + disability_percent_65to74_female)

basic_model <- lm(basic_regression_formula, df)

glance(basic_model) %>%
  kable()

tidy(basic_model) %>%
  mutate(significant = if_else(p.value < .05, TRUE, FALSE)) %>%
  kable()
```

## Basic Model Excluding Cleveland

```{r}
df_no_cle <- df %>%
  filter(county != "Cuyahoga")

basic_model_no_cle <- lm(basic_regression_formula, df_no_cle)

glance(basic_model_no_cle) %>%
  kable()

tidy(basic_model_no_cle) %>%
  mutate(significant = if_else(p.value < .05, TRUE, FALSE)) %>%
  kable()
```

## Tobit Model

```{r}
#test <- tobit(basic_regression_formula, left = 1, data = df)
#summary(test)
#tobit_results <- VGAM::vglm(basic_regression_formula, VGAM::tobit(type.f = "cens"), data = df)
#summary(tobit_results)
tobit_results <- censReg::censReg(basic_regression_formula, left = 0.5066819, data = df)
summary(tobit_results)
```

if tobit coefficients are very similar to simple linear regression coefficients, then censoring is not a big issue (if I understood Denise correctly).