# Conclusion {-}

The current opioid epidemic is the worst substance abuse epidemic in US history. Opioids are both uniquely effective at treating pain and uniquely addictive among substances of abuse. While opioid abuse has a variety of negative health effects, the largest problem with its usage is overdosing, in which an excessive quantity of opioids causes the user's respiratory system to shut down, leading to death. With synthetic opioids such as Fentanyl, death can come in as little as two minutes after consumption. Deaths from opioid overdoses kill more Americans each year than car crashes, gun violence, or HIV/AIDS did at its peak. In this thesis, I examined the economic and demographic determinants of the fatal opioid overdose rate in counties in Ohio.

Four explanatory variables have a statistically significant impact on the fatal opioid overdose rate. As individual income per capita increases, the opioid overdose death rate increases. As the percentage of adults with at least a bachelors degree increases, the fatal overdose rate decreases. As the percentage of the county that is black increases, the overdose death rate increases. Finally, as the percentage of women aged 35 to 64 with a disability increases, the opioid overdose death rate increases.

Based on these findings, promoting higher education attainment is the most effective strategy to reduce demand for opioids when only considering broad social policy. Due to the relatively low impact that higher educational attainment has, coupled with the high cost and extended timeframe of such an intervention, I believe that increasing access to treatment for addicts and distributing naloxone are likely the most cost effective ways to reduce the opioid overdose death rate in Ohio. I hope that my future work on the HEALing Communities Study, which is assesing the effectiveness and cost of various opioid addiction interventions in Ohio, Massachusetts, New York, and Kentucky, will help determine the best way to reduce opioid abuse and save lives.